#!/data/data/com.termux/files/usr/bin/bash
#Script creado por: d4rk516n5

clear
echo "Bienvenido a:" | lolcat
figlet d4rk51te | lolcat -a
date | lolcat
sleep 5
clear

#Actualizacion de Repositorios
echo "Se actualizara tu terminal"
sleep 1
clear
echo "Actualizando terminal... -"
sleep 1
clear
echo "Actualizando terminal... / "
sleep 1
clear
echo "Actualizando terminal... -"
sleep 1
clear
echo "Actualizando terminal... \ "
sleep 1
clear
pkg install unstable-repo
pkg upgrade
pkg update -y
